[package]
name = "aptos-experimental-active-state-set"
description = "Aptos Active State Set"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-config = { workspace = true }
aptos-crypto = { workspace = true }
aptos-crypto-derive = { workspace = true }
aptos-db = { workspace = true }
aptos-experimental-runtimes = { workspace = true }
aptos-infallible = { workspace = true }
aptos-jellyfish-merkle = { workspace = true }
aptos-logger = { workspace = true }
aptos-metrics-core = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-schemadb = { workspace = true }
aptos-scratchpad = { workspace = true, features = ["fuzzing", "bench"] }
aptos-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
fail = { workspace = true }
once_cell = { workspace = true }
rayon = {workspace = true}
rand = {workspace = true}
serde = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }
aptos-profiler = { workspace = true }

[dev-dependencies]
mockall = "0.10.2"